In [164]:
import numpy as np
from interface import *

In [ ]:
#a = np.random.randint(0,100,96).reshape(2,3,4,4)

In [102]:
a[0,...]

array([[[75, 74, 49, 37],
        [20, 78, 34, 40],
        [57,  0, 71, 78],
        [26, 44, 62, 78]],

       [[74, 35, 96, 98],
        [97, 43, 92, 12],
        [43, 29, 72, 22],
        [73, 69, 41, 34]],

       [[81, 15, 72, 63],
        [29, 45, 71,  0],
        [26, 60, 91, 10],
        [ 9, 51, 82, 35]]])

In [137]:
a[0,...].reshape(3,2,2,2,2)[0]

array([[[[75, 74],
         [49, 37]],

        [[20, 78],
         [34, 40]]],


       [[[57,  0],
         [71, 78]],

        [[26, 44],
         [62, 78]]]])

In [147]:
a[0,...].reshape(3,2,2,2,2)[0].transpose(0,2,1,3)

array([[[[75, 74],
         [20, 78]],

        [[49, 37],
         [34, 40]]],


       [[[57,  0],
         [26, 44]],

        [[71, 78],
         [62, 78]]]])

In [150]:
a[0,...].reshape(3,2,2,2,2)[0].transpose(0,2,1,3).reshape(2,2,4)

array([[[75, 74, 20, 78],
        [49, 37, 34, 40]],

       [[57,  0, 26, 44],
        [71, 78, 62, 78]]])

In [190]:
gamma = np.array([144., 537., 647.])
beta=np.array([-722., -281.,  880.])
running_mean=np.array([-437.,  -38.,  839.])
running_var=np.array([681., 212., 964.])
inputs=np.array([[[[ 217.]],
                   [[-598.]],
                   [[ 969.]]],
                  [[[ 413.]],
                   [[-911.]],
                   [[ 977.]]]])
              

In [191]:
momentum = 0.9
mean_value = np.mean(inputs, axis=(0,2,3), keepdims=True)
var_value = np.var(inputs, axis=(0,2,3), keepdims=True)
forward_centered_inputs = inputs - mean_value
forward_inverse_std = 1/np.sqrt(eps + var_value)
forward_normalized_inputs = forward_centered_inputs * forward_inverse_std

In [192]:
running_mean = momentum * running_mean + (1 - momentum)* mean_value.ravel()
running_var = momentum *running_var + (1-momentum) * var_value.ravel()

In [193]:
forward_normalized_inputs = (inputs - running_mean[None,:,None,None])/np.sqrt(eps + running_var[None,:,None, None])

In [189]:
forward_normalized_inputs.shape

(2, 3, 1, 1)

In [197]:
final = gamma[None,:,None,None] * forward_normalized_inputs + beta[None,:,None,None]

In [198]:
final.shape

(2, 3, 1, 1)

In [104]:
a[0,...].reshape(3,2,2,2,2)[0,0]

array([[[75, 74],
        [49, 37]],

       [[20, 78],
        [34, 40]]])

In [ ]:
a[0,...].reshape(3,2,2,2,2)[0,0]

array([[[75, 74],
        [49, 37]],

       [[20, 78],
        [34, 40]]])

In [98]:
tester

array([[[75, 74],
        [49, 37]],

       [[20, 78],
        [34, 40]]])

In [99]:
-np.mean( (y_gt * np.log(y_pred)).sum(axis=1),keepdims=True)

array([0.42523304])

In [100]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)

    Return a new array of given shape and type, filled with zeros.

    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.

